### PR TITLE
update Fabric8 Kubernetes Client to 4.10.2

### LINKED ISSUE #1118: Upgrade to kubernetes-client 4.2.2.
Kubernetes Client releases prior to 4.2.0 don't handle well cases where a single `Kind` exists under multiple `apiVersions`.

So, we need to upgrade to the latest 4.2.x (currently being 4.2.2), to get that fix.

### PR DESCRIPTION
**Pull request by Ladicek**
This is to support latest Kubernetes and OpenShift releases,
where the old Fabric8 Kubernetes Client doesn't work correctly.

This commit also updates the Snowdrop Istio Java API to
a version that also uses Fabric8 Kubernetes Client 4.10.2.
There's currently no Snowdrop Istio Java API release that
uses Fabric8 Kubernetes Client 4.10.3, which is why this
commit only updates to 4.10.2.

Fixes #1118

### CODE REVIEW

**Comment by Ladicek** [comment]
I'd like to highlight that there's a TON of failing tests (at least for me). I started fixing them, but it takes a lot of time, since they are hard to debug. So I'm submitting just the commit that updates Fabric8 Kubernetes client, because I know of at least 2 teams that would need this. (Also if Arquillian Cube is essentially dead, we would also love to know :-) )

**Comment by bartoszmajsak** [comment]
> I'd like to highlight that there's a TON of failing tests (at least for me).

Are you saying that this PR breaks tests? Which tests are you referring to - CI ran against Openshift 3.x? 

> So I'm submitting just the commit that updates Fabric8 Kubernetes client

Can't really accept PR which breaks things. We have to figure out what's the actual issue here and decide on the way we resolve it. What are the fixes you managed to apply to make some tests green so far?

> Also if Arquillian Cube is essentially dead, we would also love to know :-)

It's not actively developed - there are no new features, but it's maintained.

**Comment by Ladicek** [comment]
I'm not saying this PR breaks tests. I'm saying there's like 10 tests failing if I run `mvn clean install` locally, while connected to some arbitrary OpenShift cluster. I don't know if there are known intermittently-failing tests or if that's just my environment, so I wanted to be explicit about that. And I wanted to get this out, because I know of people who need it.

I'll try to find some time to investigate, but as I said, it isn't exactly easy :-)

**Comment by bartoszmajsak** [comment]
> I'm not saying this PR breaks tests. I'm saying there's like 10 tests failing if I run `mvn clean install` locally, while connected to some arbitrary OpenShift cluster.

Ok, that info helps :) Let me have a look at it on my side too.

**Comment by Ladicek** [comment]
Closing this as I've migrated off of Arquillian Cube.

**Pull request closed without merging**
