### PR TITLE
chore(deps): enable Dependabot v2'

### PR DESCRIPTION
**Pull request by sullis**
https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

### CODE REVIEW

**Review by rhusar — APPROVED** [review]
LGTM

**Comment by rhusar** [comment]
@fabiobrz Sounds like this should have gone in long time ago..

**Comment by fabiobrz** [comment]
> @fabiobrz Sounds like this should have gone in long time ago..

+1, thanks @rhusar - we've got quite a bit of them that we should check... Oh, time... 
Adding to the TODOs... :slightly_smiling_face:

**Comment by fabiobrz** [comment]
Right, it looks like we do have a bunch of PRs from dependantbot, including one by dependantbot-preview itself.
Anyway, changes LGTM, thanks @sullis! 
Let's start by merging this one, and see whether some of the existing ones get closed automagically.

**Review by fabiobrz — APPROVED** [review]

**Comment by fabiobrz** [comment]
It ended up in master, sure :smile: - ok then, let's backport to `main`

**Comment by rhusar** [comment]
@fabiobrz Why on earth would there be both main and master branches?! The branch should have been just renamed and then all existing PRs get automatically fixed by Github..

**Comment by fabiobrz** [comment]
Eh... It happened (or didn't, actually) here: https://github.com/arquillian/arquillian-cube/pull/1299

We've been merging changes into master and then we basically branched main out of it, IIRC.

I know @rhusar, bad move, but it's gone now 🙁... Any suggestions to fix other than pruning + cloning what's left?

**Comment by rhusar** [comment]
> Eh... It happened (or didn't, actually) here: #1299
> 
> We've been merging changes into master and then we basically branched main out of it, IIRC.
> 
> I know @rhusar, bad move, but it's gone now 🙁... Any suggestions to fix other than pruning + cloning what's left?


Not sure what's the branching strategy, but quick look:

So `master` is now effectively support branch for 1.x stream? So you can just rename it to `1.x` then.

And if `2.0.x` is already completely merged into `main`, delete that.

**Comment by fabiobrz** [comment]
Renaming master to 1.x could definitely be a good point, specifically in order to get to a release soon.

@jimma suggested a similar thing. I'll give this a try and we'll see how it goes.

+1 on deleting the 2.x branch.

**Pull request merged**
