### PR TITLE
[ISSUE #392] Fixed: Using star operator with @HostPort and @DockerUrl

### PR DESCRIPTION
**Pull request by pwoelfle**
#### Short description of what this resolves:
As reported in [ISSUE 392](https://github.com/arquillian/arquillian-cube/issues/392), it is not possible to use `@HostPort` and `@DockerUrl` when using the star operator.

**Fixes**: #392

### CODE REVIEW

**Comment by lordofthejars** [comment]
Overall the PR is really awesome and fixes in a clean way the problem you mention, but I have got a deep question. Suppose we have a Docker Host with same container started in parallel with id (`tomcat_1234` and `tomcat_5678`). Then you do `@HostPort(containerName = "tomcat*", value = 8080)` and here it is injected the first one found. Is it right to have it in that way? I suppose that from the point of view of test it has not much sense which one is taken, but if it is always returned the same (first) then you are not using all the resources. But of course maybe I am missing something.

**Comment by pwoelfle** [comment]
Using Gradle, the parallel test execution is realized by splitting the tests in separate JVM processes. But within each process only one test is execute per time [1]. So only one `tomcat_[UUID]` should be present on execution of a test, because `LocalCubeRegistry` instance is per JVM process.

I'm not very familiar with Maven, but it seems that Maven allow parallel execution on method level. 
I will verify the behaviour and will post my results here.

[1] https://docs.gradle.org/current/userguide/java_plugin.html#sec:test_execution
[2] http://maven.apache.org/surefire/maven-surefire-plugin/examples/fork-options-and-parallel-execution.html

**Comment by lordofthejars** [comment]
@pwoelfle yes you are right in case of more than one JVM, but I know that in Maven you can use parallel in same jvm, but well you have also the option to fork the execution.

**Comment by pwoelfle** [comment]
@lordofthejars 
If I understand the existing code right, then a starred container defined in an `arquillian.xml` is auto-started. After all tests finished the container is destroyed.
Only using container objects will destroy the container after class, won't it? (See `org.arquillian.cube.docker.impl.client.containerobject.AfterClassContainerObjectObserver`)

So there is only one container `tomcat_[UUID]` which is used by all tests. Even when forking the tests, then there is one container per JVM process, which is used for all tests of the forked JVM process. I tried this with simple tests. 

This means that the current solution of parallism only provides the possibility to run multiple builds of the same project. This is the case on CI servers, where multiple builds with different branches or commits are running the same time on the same node.

Parallism on test level would be a new feature in my opinion. There should be a pool of containers, which belongs to a starred container. The parallel executed tests could then exclusivly request a container and return the instance back to pool after finish. This feature would only make sense for Maven, because there multiple tests can run in parallel within the same JVM process.

Btw is there a way to force container restart for each test or test class?

**Comment by lordofthejars** [comment]
@pwoelfle I agree with you, I think for now the solution is clear and it works. Maybe it has no sense at all for now implementing more complex things if no one requests because of an specific reason. For this reason I choose to merge the PR :)

As you said there is no way to fore a restart of a container per test class, but we could add this property as container property which by default is false.

**Pull request merged**
