### PR TITLE
Add the ability to inject a URL from a Route in an arbitrary namespace

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #1063

### CODE REVIEW

**Comment by geoand** [comment]
Yes of course, forgot about that :)

**Comment by geoand** [comment]
Docs updated

**Comment by lordofthejars** [comment]
@geoand 1.17.1 released, now just need to wait until jboss nexus is synced with maven central.

**Comment by geoand** [comment]
Awesome, thank you very much @lordofthejars!

**Comment by geoand** [comment]
@lordofthejars Has perhaps sync to Maven Central failed? Release `1.17.1` still hasn't propagated

**Comment by lordofthejars** [comment]
I was thinking exactly the same, I don't know why this is happening because
in jboss nexus it is released.

El dc., 18 de jul. 2018 a les 11:18, Georgios Andrianakis (<
notifications@github.com>) va escriure:

**Comment by lordofthejars** [comment]
@geoand can you try to add in the project to see if it is downloaded? Sometimes what's happening is that the index process has not happened but the artifacts are published.

**Comment by geoand** [comment]
Still no love from Maven Central unfortunately. I tried it locally and I also relaunched [this](https://circleci.com/gh/snowdrop/spring-boot-istio-distributed-tracing-booster/21) CircleCI job that contains the artifact as a dependency.

There is no rush with this, I can wait, I was just wondering if something went wrong :)

**Comment by geoand** [comment]
@lordofthejars Perhaps a follow up `1.17.2` release is needed? Unfortunately `1.17.1` still hasn't been propagated to Central

**Comment by lordofthejars** [comment]
I am talking about this internally in RH

El dj., 19 de jul. 2018 a les 8:44, Georgios Andrianakis (<
notifications@github.com>) va escriure:

**Comment by geoand** [comment]
Cool, thanks for the update!

**Comment by lordofthejars** [comment]
Synced.

**Comment by geoand** [comment]
Yes, tried it a few hours ago and it worked like a charm!
Thanks!

**Pull request merged**
