### PR TITLE
Host

### PR DESCRIPTION
**Pull request by jwendell**
This change is [Reviewable](https://reviewable.io/reviews/arquillian/arquillian-cube/419)

### CODE REVIEW

**Comment by lordofthejars** [comment]
Currently we are reworking the openshift solution to be aligned with fabric8 library. You can see the PR https://github.com/arquillian/arquillian-cube/pull/414 which should be ready to merge, it only needs to be reviewed. If you want feel free to review it too.

**Comment by rcernich** [comment]
@jwendell please review #414 to verify it doesn't break anything in ce-arq.

**Comment by jwendell** [comment]
ping

so, the new openshift solution makes this patch obsolete? (I just reached this bug)

**Comment by jwendell** [comment]
just pulled the latest changes (like upgrading to newer undertow) but the issue is still there...

**Comment by lordofthejars** [comment]
@jwendell so we need to merge this issue right?

**Comment by jwendell** [comment]
imo, yes.

**Comment by lordofthejars** [comment]
then it is easy, I merge it, and we see since we can always revert the change.

**Comment by lordofthejars** [comment]
@jwendell did it work?

**Pull request merged**
