### PR TITLE
Allow custom beforeStopStrategies

### PR DESCRIPTION
**Pull request by jelmew**
#### Short description of what this resolves:
Link to issue: https://github.com/arquillian/arquillian-cube/issues/646
This is a WIP of a proposal allow customBeforeStopEvents. Since I'm still a rookie, I would like to receive feedback whether this is an appropriate idea and implementation (in terms of structure, packaging,general idea, variable naming, etc). Furthermore, what is the convention in terms of testing in arquillian-cube?

#### Changes proposed in this pull request:
-  Added beforeStopStrategy that can be used in beforeStop to do custom things before stopping, as described in the issue.

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Heya, we just did big shabang reformatting, luckily you only have one conflict :) 

If you are using IDEA can you import these settings? https://github.com/arquillian/code-settings

**Comment by jelmew** [comment]
Hiya,

Will do. Thanks for the info.

**Comment by bartoszmajsak** [comment]
No no, thanks for your contribution :) We will review with @lordofthejars in the following days and get back with feedback .

**Comment by lordofthejars** [comment]
Really awesome commit, just one thing, can you write a unit/ftest and update documentation as well? Everything else it is just perfect.

**Comment by jelmew** [comment]
Hi,
Good to hear that the idea is good. I'l write unit tests and documentation.

**Comment by jelmew** [comment]
I've written test and documentation and removed the WIP tag. Please take a look if someone has time.

**Comment by lordofthejars** [comment]
Looks good to me, really thank you for your help, this change is going to be a part of 1.1.0 release.

**Pull request merged**
