### PR TITLE
fix(#887): Removes HttpClient module

### LINKED ISSUE #887: Removes httpclient module
##### Issue Overview

Removes httpclient module and substitute the places where it is used by `okhttp`

### PR DESCRIPTION
**Pull request by lordofthejars**
#### Short description of what this resolves:

Removes HttpClient module and instead use okhttp.

#### Changes proposed in this pull request:

- Removes HttpClient module
- Adapt code to use okhttp

Fixes #887

### CODE REVIEW

**Comment by jwendell** [comment]
hmm, we are a heavy user of this...

**Comment by alesj** [comment]
Yeah, I think this just needs to be re-written to use OKHttpClient, instead of ApacheHC.
As CE's testsuite uses this a lot.

**Comment by lordofthejars** [comment]
Already done in PR

**Comment by jwendell** [comment]
I think what Ales said was to change the implementation to use okhttp but keep the interface.

**Comment by lordofthejars** [comment]
Interface was used just in one place, so not sure if it has much sense
maintaing abstraction. Also okhttp offers this kind of abstraction

**Comment by alesj** [comment]
It's used externally - - the interface.
So CE won't have to change all tests.

The abstraction was there to unify http API usage.

**Comment by lordofthejars** [comment]
Ok, but then why an abstraction of an http client should be provided by Cube?

**Comment by alesj** [comment]
@lordofthejars yes, I agree, no need to port that code over to Cube.

**Pull request merged**
