### PR TITLE
Move special Cube methods to Metadata Objects

### LINKED ISSUE #246: Remove cubeId from methods on Cube interface
Methods in question:

* copyFileDirectoryFromContainer
* copyLog
* top

### LINKED ISSUE #247: Move non basic methods from Cube interface into Metadata
Methods like:

* copyFileDirectoryFromContainer
* copyLog
* top
* getBuildImage (to come)

could be moved into the has|getMetadata feature of a Cube. 

A top level CubeMetadata interface should be created to allow easy IDE lookup of possible metadata featues, e.g.:

```java
<? extends CubeMetadata> boolean hasMetadata(Class<T> type);
<T extends CubeMetadata> T getMetadata(Class<T> type);
<T extends CubeMetadata> void addMetadata(T data);
```

### PR DESCRIPTION
**Pull request by aslakknutsen**
* Introduce CubeMetadata interface to bind all Metadata objects

Update Cube interface:

    <X extends CubeMetadata> boolean hasMetadata(Class<X> type);
    <X extends CubeMetadata> void addMetadata(Class<X> type, X impl);
    <X extends CubeMetadata> X getMetadata(Class<X> type);

Move the following methods from the Cube interface:

* copyFileDirectoryFromContainer
* changesOnFilesystem
* copyLog
* top

To the new Metadata objects:

* CanCopyFileDirectoryFromContainer (impl CopyFileDirectoryFromContainer)
* CanSeeChangesOnFilesystem (impl ChangesOnFilesystem)
* CanCopyLog (impl CopyLog)
* CanSeeTop (impl GetTop)

fixes #246
fixes #247

### CODE REVIEW

**Comment by aslakknutsen** [comment]
Not sure if those are the best names, but.. 

```java
if (cube.hasMetadata(CanCopyFileDirectoryFromContainerLog.class))
  cube.getMetadata(CanCopyFileDirectoryFromContainer.class).copy(x, y)
```

**Comment by lordofthejars** [comment]
@aslakknutsen I think names are ok because you can read exactly what you want to do, what I am not sure if we could group them in other way. For example CanCopyFromContainer (which includes the CopyLog and the CopyFiles)

**Comment by aslakknutsen** [comment]
Sure, we could make that one.

**Comment by aslakknutsen** [comment]
CanCopyFilesFromContainer and CanCopyLog now merged into one; CanCopyFromContainer

**Pull request merged**
