### PR TITLE
fix config value lookup ordering

### LINKED ISSUE #816: properties in arquillian.xml take precedence over system properties
##### Issue Overview

I have `arquillian.xml` looking like this:

```xml
<arquillian>
  <extension qualifier="openshift">
    <property name="namespace.use.current">true</property>
    <property name="env.init.enabled">true</property>
  </extension>
</arquillian>
```

(Ignore the `env.init.enabled` bit, I know it defaults to `true`, I include it just to make it clear that I depend on that behavior.)

I intentionally set `namespace.use.current` to `true` here so that the tests _default_ to running in current namespace. But sometimes, I want Cube to create the temporary `itest-xxxx` namespace and use it, and I'm invoking Maven with `-Dnamespace.use.current=false` to do that.

##### Expected Behaviour

A temporary namespace is created and used.

##### Current Behaviour

Current namespace is used even though I specify `-Dnamespace.use.current=false`.

##### Steps To Reproduce
1. git clone -b arquillian-cube http://github.com/Ladicek/wfswarm-rest-http/
2. cd wfswarm-rest-http
3. mvn clean verify -Popenshift,openshift-it -Dnamespace.use.current=false -DenableImageStreamDetection=true

##### Additional Information

This is caused by the `org.arquillian.cube.impl.util.ConfigUtil` implementation. The first method's javadoc actually says

```
The lookup order is system > env > map > defaultValue.
```

but the implementation doesn't conform to that javadoc.

I can send a PR, it's a pretty simple change, but I want to confirm first that it's really a bug. (I think it is.)

### PR DESCRIPTION
**Pull request by Ladicek**
Fixes #816.

### CODE REVIEW

**Comment by Ladicek** [comment]
Fixed `getKubernetesConfigurationUrl`, the test failure revealed an actual issue, yay tests!

**Comment by lordofthejars** [comment]
@Ladicek So I need to wait before merging this PR isn't it?

**Comment by Ladicek** [comment]
Do you? The tests are green now.

**Comment by lordofthejars** [comment]
Ok, I didn't understand if you did more modifications or not. 

Cool.

**Comment by Ladicek** [comment]
Ah, sorry. I broke one test originally, but I fixed the code and all tests pass now. So this is ready to go from my POV.

**Comment by lordofthejars** [comment]
Thank you so much.

**Pull request merged**
