### PR TITLE
Upgrade to UnderTow 1.3.24.

### PR DESCRIPTION
**Pull request by alesj**
This change is [Reviewable](https://reviewable.io/reviews/arquillian/arquillian-cube/425)

### CODE REVIEW

**Comment by lordofthejars** [comment]
Currently we are reworking the openshift solution to be aligned with fabric8 library. You can see the PR #414 which should be ready to merge, it only needs to be reviewed. If you want feel free to review it too.

**Comment by spolti** [comment]
This PR fixes this: java.lang.NoSuchMethodError: io.undertow.client.UndertowClient.connect(Ljava/net/URI;Lorg/xnio/XnioWorker;Lorg/xnio/ssl/XnioSsl;Lorg/xnio/Pool;Lorg/xnio/OptionMap;)Lorg/xnio/IoFuture;

**Comment by lordofthejars** [comment]
@spolti @alesj I can merge this change right?

**Comment by alesj** [comment]
Sure.

**Pull request merged**
