### PR TITLE
Fixed failing tests due to incorrect usage of ftpclient

### PR DESCRIPTION
**Pull request by dipak-pawar**
**Fixes**: #750

### CODE REVIEW

**Comment by lordofthejars** [comment]
Looks goot to me, I'll try on Mac when I have some time.

**Comment by lordofthejars** [comment]
In case of `docker-machine` it is not working because of timeout `java.net.ConnectException: Operation timed out`.

**Comment by dipak-pawar** [comment]
@alex Are you getting `ConnectException` for initializing client or for uploading file?

**Comment by lordofthejars** [comment]
@dipak-pawar During upload

```
at java.net.Socket.connect(Socket.java:589)
	at org.apache.commons.net.ftp.FTPClient._openDataConnection_(FTPClient.java:924)
	at org.apache.commons.net.ftp.FTPClient._storeFile(FTPClient.java:657)
	at org.apache.commons.net.ftp.FTPClient.__storeFile(FTPClient.java:643)
	at org.apache.commons.net.ftp.FTPClient.storeFile(FTPClient.java:2034)
	at org.arquillian.cube.containerobject.FtpClient.uploadFile(FtpClient.java:33)
	at org.arquillian.cube.containerobject.FtpClientTest.should_upload_file_to_ftp_server(FtpClientTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
```

**Comment by dipak-pawar** [comment]
@alex So currently What is `hostip` value? Is it your host or `docker machine ip`?

**Comment by lordofthejars** [comment]
yes it is the ip of `docker machine`

**Comment by dipak-pawar** [comment]
@lordofthejars Can you try `ftpClient.enterLocalActiveMode();` by removing `ftpClient.enterLocalPassiveMode();` from [FTPClient](https://github.com/dipak-pawar/arquillian-cube/blob/38a6db6cb6d928c77d2abe2646c23f42ee77a257/docker/ftest-docker-containerobject/src/test/java/org/arquillian/cube/containerobject/FtpClient.java#L28)

**Comment by lordofthejars** [comment]
Yes with the change you mention it worked really well.

**Comment by lordofthejars** [comment]
Thanks @dipak-pawar

**Pull request merged**
