### PR TITLE
Namespace in annotation named

### PR DESCRIPTION
**Pull request by strowk**
#### Short description of what this resolves:
Support more than one namespace in one test
https://github.com/arquillian/arquillian-cube/issues/361

#### Changes proposed in this pull request:

- Added ability to specify namespace with annotation `@Named`
- Added back compatible method getNamespace in AbstractKubernetesResourceProvider
- Added using of specified namespace in implementations of AbstractKubernetesResourceProvider

### CODE REVIEW

**Comment by lordofthejars** [comment]
Thank you very much for your help, just one minor thing, can you update docs as well? 

Thanks :)

**Comment by jwendell** [comment]
Also, please write a test for it.

**Comment by strowk** [comment]
I added tests and docs, but apparentely current travis configuration tries to run tests on different versions of openshift simultaneously which works pretty random. 

But i tried to run it one by one:
https://github.com/arquillian/arquillian-cube/pull/872/commits/a013a4102678e624b581c305bb3b0d0b4c3f1f06 
https://travis-ci.org/arquillian/arquillian-cube/builds/310507618

https://github.com/arquillian/arquillian-cube/pull/872/commits/c3ab12274f1451dd9f40c606fe8fc92642ca03dd
https://travis-ci.org/arquillian/arquillian-cube/builds/310513570

It worked, so tests looks passed to me, even if it fails with both OC_VERSION="v3.6.0" and OC_VERSION="v3.6.1" enabled it could fail.

**Comment by lordofthejars** [comment]
Thank you very much for your help on improving Cube.

**Pull request merged**
