### PR TITLE
Implements several issues for next version of Cube

### PR DESCRIPTION
**Pull request by lordofthejars**

### CODE REVIEW

**Comment by lordofthejars** [comment]
So true, sorry I start coding and coding and I don't remember to document.

**Comment by aslakknutsen** [comment]
Not a fan of the new 'commons' dependencies, but beyond that looks good. :)

**Comment by lordofthejars** [comment]
I know you would said this, but they are not new, they are a dependency from other projects(docker-java) so I am only using them. commons-lang is used by cube-core.

**Comment by aslakknutsen** [comment]
sure, still not a fan. :)

**Comment by lordofthejars** [comment]
not a big fan but commons-lang in our case is really helpful. The only one that I might replace would be the MapUtils class for one of our own. I would do it in near future.

**Comment by lordofthejars** [comment]
https://github.com/arquillian/arquillian-cube/issues/207

**Comment by aslakknutsen** [comment]
:+1:

**Comment by lordofthejars** [comment]
So ready to merge?

**Comment by aslakknutsen** [comment]
yea :)

**Pull request merged**
