### PR TITLE
Port-fowarder does not accept you to specify the local port the same as the container.

### PR DESCRIPTION
**Pull request by spolti**
This change is [Reviewable](https://reviewable.io/reviews/arquillian/arquillian-cube/336)

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Thanks for your contribution! It would be double awesome if you could cover this new functionality in in unit tests. Would it be possible? :)

**Comment by spolti** [comment]
Sure, I'll commit as soon as possible.

**Comment by spolti** [comment]
Please, wait until the next commit, I am changing the way to allocate the ports.

**Comment by spolti** [comment]
Now the accepted values are:
<pod>:<port> - backward compatibility (use aleatory port)
<pod>:<port>:<port> - map the same port
<pod>::<port> - map the same port
<pod>:0:<port> - map an aleatory port

**Comment by spolti** [comment]
Hello guys, any new on this?

**Comment by lordofthejars** [comment]
Thanks for the contribution. Much appreciated.

**Pull request merged**
