### PR TITLE
chore(deps): bumps docker-java to 3.1.5

### PR DESCRIPTION
**Pull request by tobiasstadler**
Upgraded docker-java to 3.1.2

### CODE REVIEW

**Comment by tobiasstadler** [comment]
@lordofthejars Could you please have a look?

**Comment by tobiasstadler** [comment]
@lordofthejars Could you please have another look and merge it? Thanks

**Comment by tobiasstadler** [comment]
Anyone willing to commit this?

**Comment by tobiasstadler** [comment]
@bartoszmajsak Could you please have a look?

**Comment by tobiasstadler** [comment]
Anyone willing to review this?

**Comment by bartoszmajsak** [comment]
Overall looks good, but I think we have to make CI green again before we can proceed further.

Did you run the build locally btw?

**Comment by tobiasstadler** [comment]
#1141 fixes CI

**Comment by tobiasstadler** [comment]
Your welcom! Could you do a Release?

**Pull request merged**
