### PR TITLE
Bump k8s-client to 2.5

### PR DESCRIPTION
**Pull request by pavolloffay**
Update k8s-client to 2.5

Resolves https://github.com/arquillian/arquillian-cube/issues/755

### CODE REVIEW

**Comment by lordofthejars** [comment]
@iocanel when you have time can you review this? Basically it seems a deep change and I don't find myself authoritative in this change at all.

**Comment by pavolloffay** [comment]
Thanks for quick the merging :100: 

@lordofthejars when do you plan a new release with this change?

**Comment by lordofthejars** [comment]
When this is fixed https://github.com/arquillian/arquillian-cube/pull/751 which we are pretty near, I'll do it, so probably today or tomorrow.

**Comment by lordofthejars** [comment]
@pavolloffay Releasing right now, I suppose that in few hours everything will be synced in maven central.

**Comment by pavolloffay** [comment]
Awesome, thanks @lordofthejars :+1:

**Pull request merged**
