### PR TITLE
Resume Docker integrations tests

### LINKED ISSUE #1302: [Integration Tests] - Replace use of tomcat:7.0.75-jre8  in tests with higher version which can work on JDK 11
##### Issue Overview

We have enforced `JDK 11` now, and `tomcat:7.0.75-jre8`  is widely used in Dockerfile in integration tests. The container starts with JDK8 but will try to load the tests servlets compiled in JDK 11 which will lead to container error:

```java
[🎩 lgao@lins-p1 arquillian-cube]$ curl -i http://localhost:8081/hello/HelloWorld
HTTP/1.1 500 Internal Server Error
Server: Apache-Coyote/1.1
Content-Type: text/html;charset=utf-8
Content-Language: en
Content-Length: 3307
Date: Tue, 16 Apr 2024 04:08:42 GMT
Connection: close

<html><head><title>Apache Tomcat/7.0.75 - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 500 - org/arquillian/cube/servlet/HelloWorldServlet has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 (unable to load class org.arquillian.cube.servlet.HelloWorldServlet)</h1><HR size="1" noshade="noshade"><p><b>type</b> Exception report</p><p><b>message</b> <u>org/arquillian/cube/servlet/HelloWorldServlet has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 (unable to load class org.arquillian.cube.servlet.HelloWorldServlet)</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>java.lang.UnsupportedClassVersionError: org/arquillian/cube/servlet/HelloWorldServlet has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 (unable to load class org.arquillian.cube.servlet.HelloWorldServlet)
	org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:3209)
	org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:1373)
	org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1861)
	org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1735)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:495)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2473)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:745)
</pre></p><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/7.0.75 logs.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.75</h3></body></html>
```

So we need to 

##### Expected Behaviour
No test failures

##### Current Behaviour

Test fail with exceptions:
```java
[INFO] Running org.arquillian.cube.servlet.HelloWorldServletIT
[ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 1.020 s <<< FAILURE! -- in org.arquillian.cube.servlet.HelloWorldServletIT
[ERROR] org.arquillian.cube.servlet.HelloWorldServletIT.should_parse_and_load_configuration_file -- Time elapsed: 0.037 s <<< ERROR!
java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:8081/hello/HelloWorld
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at org.arquillian.cube.servlet.HelloWorldServletIT.should_parse_and_load_configuration_file(HelloWorldServletIT.java:54)

```

##### Steps To Reproduce

```
cd arquillian-cube/docker/ftest-docker-compose
mvn clean install -Dfailsafe.groups=org.arquillian.cube.docker.impl.requirement.RequiresDocker
```

##### Additional Information

```
JDK: 11
main branch
```

### LINKED ISSUE #1315: Make Docker integration tests green again, and resume the related CI execution
##### Issue Overview

Resume Docker integration tests.

##### Expected Behaviour

The tests that verify the Arquillian Cube Docker integration should pass, and the CI script should be fixed in order to resume the execution of such tests.

##### Current Behaviour

The Arquillian Cube integration tests for Docker are failing, and the CI doesn't execute them, see https://github.com/arquillian/arquillian-cube/blob/main/.circleci/config.yml#L19 (notice the `package` goal...)

##### Steps To Reproduce
1. 
```
mvn clean package -Dfailsafe.groups=org.arquillian.cube.docker.impl.requirement.RequiresDocker -Dcontainerless.skip.tests=true
``` 

##### Additional Information

N/A

### PR DESCRIPTION
**Pull request by fabiobrz**
The changes here aim at fixing the Docker integration tests after the recent updates, and to enable GitHub workflow based CI checks

#### Short description of what this resolves:
Fixing implementation after changes to support JDK 11, resuming Docker integration tests, upgrading dependencies where required, enabling proper CI check via GitHub workflow
The CI checks which are executed with the changes in this PR will actually execute Docker integration tests. 

#### Changes proposed in this pull request:

- Some fixes to the functional classes, mainly due to previous updates, e.g.: adding support for JDK11
- Version bump, both at POM dependencies level (e.g.: JBoss parent, docker-java, etc.), and images version used in functional tests (e.g.: WildFly image), which in turn implies some changes to the test deployments, most notably moving from `javax.*` to `jakarta.*` 
- Bumping the Docker server API versionused by Docker integration tests and `containerless` to 1.43, which is the latest supported by docker-java 3.4.0
- Replacement of no longer available images used in Docker integration tests, e.g.: `jonmorehouse/ping-pong` is replaced by `hashicorp/http-echo:alpine` - thanks to the work done by @gaol in #1306 here - and by `tsongpon/pingpong`, depending on the related configuration requirements
- Bumping Tomcat dependencies in Docker integration tests, from 7 to 10. Changes to the server image definition (e.g.: exposing the `manager` ap which is needed to deploy), and to the related test deployments, most notably moving from `javax.*` to `jakarta.*` have been introduced accordingly
- Docker container object related integration tests using FTP and SSH containers, have been updated to replace no longer available images, or to update required dependencies
- The H2 database image used by Docker integration tests has been replaced as well by a more recent one
- Resuming the Docker integration tests execution in the GitHub workflow based CI script, and fix some tests which were expecting to use ports which might not be available in the CI environment (e.g.: 5000 for minkube, or 8089 for splunk) 

**Follow up issues**
The following is a list of issues that have been logged as a follow up to the actions described above: 
- The Arquillian core dependency version should be updated asap, in order to remove leftover dependency from javax.* artifacts in the classpath, tracked by #1318 
- Unify the approach on Docker integration tests which use a ping-pong image/test method: i.e. pingpong vs. http-echo - can be tracked by #1303 and done in #1306, provided the issues and PR description is updated to reflect the scope.
- Verify what `docker-compose` versions are actually supported, and document/test accordingly. Evaluate whether to reintroduce any docker v1 removal change which might have happened lately, also because the documentation states thata the CUBE format only support docker compose v1? Tracked by #1319 

Fixes #1315, resolves #1302

### CODE REVIEW

**Review by gaol — COMMENTED** [review]
Overall it looks great unless some of my overcritical comments  :+1: :)

**Comment by fabiobrz** [comment]
> Overall it looks great unless some of my overcritical comments 👍 :)

Thanks for your review @gaol - actually pretty good points, so I've fixed the changes accordingly.

**Review by gaol — APPROVED** [review]
LGTM !

**Comment by jimma** [comment]
This looks good to me . Nice work @fabiobrz !

**Review by jimma — APPROVED** [review]

**Pull request merged**
