### PR TITLE
resolves issue #310 by rebuilding dockerClient after a Docker build command

### PR DESCRIPTION
**Pull request by foxlegend**
Actually when trying to build an image with Arquillian Cube, docker host throwed
the exception message: http: Hijack is incompatible with use of CloseNotifier.
It seems to be a problem with go and should be fixed in go 1.6 (and maybe in
Docker 1.11.0).
For now, closing and recreating the Docker client after a call to the build Docker
command seems to solves the problem.

I let you have a look to the code. If you have a cleaner solution I could write the enhancement.

I'm sorry for the delay…

### CODE REVIEW

**Comment by lordofthejars** [comment]
No worries for the delay, I just only asking to know when we could release a new version fixing this :+1:  Thank you very very much for your collaboration.

**Comment by lordofthejars** [comment]
Thank you so much for this workaround.

**Comment by lordofthejars** [comment]
BTW do you think it would be possible to have a hello world project that reproduces it? So it will be a way to see if it is fixed in the future or not.

**Comment by foxlegend** [comment]
Yes, I think it would be possible. I'll create such a project when I have some time ;)

**Comment by lordofthejars** [comment]
Thank you so much, basically to know if it is fixed on docker and go or not
:)

El dv., 18 març 2016 a les 15:54, David Pequegnot (<notifications@github.com>)
va escriure:

**Pull request merged**
