### PR TITLE
build(deps): bumps Arquillian to 1.5.0.Final

### PR DESCRIPTION
**Pull request by tobiasstadler**

### CODE REVIEW

**Comment by tobiasstadler** [comment]
@bartoszmajsak Could you please have alook and do a release?

**Comment by tobiasstadler** [comment]
Fan anyone please Review this? Mayen @bartoszmajsak or @lordofthejars?

**Comment by bartoszmajsak** [comment]
> anyone please Review this? 

Thanks for that update. I struggle with running tests on my machine - getting bunch of errors (in general from master), so I have to fix those before I can cut the release. Working on it today

**Comment by tobiasstadler** [comment]
Thank You!

**Pull request merged**
