### PR TITLE
build(deps): updates docker-java to version 3.2.0

### PR DESCRIPTION
**Pull request by tobiasstadler**

### CODE REVIEW

**Comment by tobiasstadler** [comment]
Would be nice

**Comment by bartoszmajsak** [comment]
Let me merge a few more things and I will do it today.

**Comment by tobiasstadler** [comment]
Thank You!

**Comment by bartoszmajsak** [comment]
@tobiasstadler it seems Travis is getting more and more unreliable. I will move that to CircleCI tonight.

**Pull request merged**
