### PR TITLE
Bump istio-java-api to 0.12

### LINKED ISSUE #1085: Update istio-java-api to 0.12
This latest version brings support for Istio 1.0.x

### PR DESCRIPTION
**Pull request by geoand**
Fixes #1085

### CODE REVIEW

**Comment by geoand** [comment]
@lordofthejars Have you perhaps had a chance to take a look at this? 

Thanks

**Comment by geoand** [comment]
@lordofthejars that is absolutely correct :)

**Comment by lordofthejars** [comment]
Thank you very much for the contribution. Whenever you  need a release just ping me or @bartoszmajsak

**Comment by geoand** [comment]
Awesome! Thanks @lordofthejars!

Actually, a release at your earliest convenience would be great :wink:

**Comment by lordofthejars** [comment]
Released of 1.18.0

**Comment by geoand** [comment]
Thanks @lordofthejars !

**Pull request merged**
