### PR TITLE
Improvements for Kubernetes and Openshift

### PR DESCRIPTION
**Pull request by iocanel**
This is now ready to review/merge.

Highlights:

1. Upgrade to the latest kubernets-client.
2. Remove the await logic from kubernetes module and use the clients `waitUntilReady`.
3. Add Openshift specific implementation for the Namespace service.

### CODE REVIEW

**Comment by lordofthejars** [comment]
@iocanel Looks good to me, just one thing, with this update are we breaking something if a user updates to this new version? So is it back-compatibilty? I just asked to add an important note on release notes or not :)

**Comment by iocanel** [comment]
@lordofthejars: I don't think that we are breaking something.

**Comment by iocanel** [comment]
@lordofthejars: can I merge that? Also can we get an alpha release out? I'd like to use that for https://github.com/redhat-ipaas/

**Comment by lordofthejars** [comment]
Can you wait until Monday or you prefer having just tomorrow?

**Comment by iocanel** [comment]
The sooner the better :-)

**Comment by lordofthejars** [comment]
@iocanel released on JBoss Nexus and it is going to be synced in maven central between next 24 hours.

**Comment by iocanel** [comment]
@lordofthejars: thank you so much!

**Comment by bartoszmajsak** [comment]
I wouldn't be so sure about the sync ;)

**Pull request merged**
